### ISSUE TITLE
Add the ability to filter which resources to load

### ISSUE THREAD

**Issue by taliaferro** [LLNL/elastic-stacker#7]
Right now, the load mechanism pulls in all files in given resource directory. For some use cases this is not enough -- at the moment the easiest way to do a selective import is to move only the dump files you want into a separate directory and load from that.

I'd like to introduce the ability to define a set of glob patterns which would be used to select or reject which dump files to load.
These could be specified in a profile, like:
```yaml
profiles:
  prod:
    include: prod_*.json
    exclude: pre_*.json
```
Or at the command line, as in `stacker roles load --include '*_admin.json' --exclude 'temp_admin.json'`.
